### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by Orgasmusbremse** [sweetriverfish/ReportMyTeam#2]
i double click it, doesn't even open, tried opening with admin, still doesn't work

**Comment by sweetriverfish** [comment]
Open it via cmd and read the error.
My guess is that you may not have .NET Runtime (v7.0) installed which is required. [x64 Windows installer](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-7.0.5-windows-x64-installer)

**Comment by Orgasmusbremse** [comment]
> Open it via cmd and read the error. My guess is that you may not have .NET Runtime (v7.0) installed which is required. [x64 Windows installer](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-7.0.5-windows-x64-installer)

thanks for the fast answer. that was exactly my problem
