### ISSUE TITLE
With the new patch 13.15 the program stopped reporting.

### ISSUE THREAD

**Issue by fazuelli** [sweetriverfish/ReportMyTeam#4]
'Log:' 
Awaiting for a game to be over.

Failed to report nickname
nickname is the current account, ignoring
Failed to report nickname
Failed to report nickname
Failed to report nickname
Failed to report nickname
Failed to report nickname
Failed to report nickname
Failed to report nickname
Failed to report nickname

**Comment by sweetriverfish** [comment]
I've released a fix, you can find it under releases
